name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install dependencies
        run: npm install

      - name: Build old version
        run: npm run build -- --output-path=dist/old

      - name: Build new version with feature flag
        run: |
          FEATURE_AUTOUPDATE=true npm run build -- --output-path=dist/new


      - name: Create root index.html
        run: |
          echo '
          <!DOCTYPE html>
          <html lang="en">
          <head>
            <meta charset="UTF-8">
            <title>Version Selector</title>
            <style>
              body { 
                display: flex;
                justify-content: center;
                align-items: center;
                min-height: 100vh;
                margin: 0;
                font-family: Arial, sans-serif;
                background: #f0f2f5;
              }
              .container {
                text-align: center;
                padding: 2rem;
                background: white;
                border-radius: 10px;
                box-shadow: 0 2px 15px rgba(0,0,0,0.1);
              }
              h1 {
                color: #2c3e50;
                margin-bottom: 2rem;
              }
              .links {
                display: flex;
                gap: 1rem;
                flex-direction: column;
              }
              a {
                padding: 1rem 2rem;
                background: #3498db;
                color: white;
                text-decoration: none;
                border-radius: 5px;
                transition: transform 0.2s, background 0.2s;
              }
              a:hover {
                background: #2980b9;
                transform: translateY(-2px);
              }
            </style>
          </head>
          <body>
            <div class="container">
              <h1>Выберите версию приложения</h1>
              <div class="links">
                <a href="old">Версия с кнопкой обновления</a>
                <a href="new">Версия с автоматическим обновлением</a>
              </div>
            </div>
          </body>
          </html>'\
          > ./dist/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./dist
